config/routes.rb
# config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Root path
  root "urls#new"

  # Resources for URLs
  # GET /urls/new – The new action in the UrlsController to render a form for creating a new URL.
  # POST /urls – The create action in the UrlsController to handle form submission and create the short URL.
  # GET /urls/:id – The show action in the UrlsController to display the details of a specific shortened URL.
  resources :urls, only: [ :new, :create, :show ]

  # Custom redirect for shortened URLs
  # Why custom? This is specifically for redirecting shortened URLs.
  get "/:short_url", to: "urls#redirect", as: :shortened

  # Resources for reports with custom API routes
  resources :reports, only: [ :index ] do
    collection do
      get :api_index
      get :api_all_urls
    end
  end
end

# get :api_index - This creates a route that maps to the api_index action in the ReportsController. The resulting route is GET /reports/api_index.
# get :api_all_urls - This creates a route that maps to the api_all_urls action in the ReportsController. The resulting route is GET /reports/api_all_urls.

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/url.rb
class Url < ApplicationRecord
  before_create :generate_short_url
  before_save :set_default_title

  validates :target_url, presence: true

  def fetch_title
    self.title = "Title Not Available" if self.title.blank?
  end

  private

  def generate_short_url
    loop do
      # Generate a short URL using SecureRandom with a length of 4 characters (Because 64 ^ 4 has total combinations enough for this use case)
      # Why no UUID? - UUID is too long, we need to keep the short url as short as possible
      self.short_url = SecureRandom.urlsafe_base64(4)
      # Ensure the generated short URL is unique
      break unless Url.exists?(short_url: short_url)
    end
  end

  def set_default_title
    self.title = "Title Not Available" if self.title.blank?
  end
end

# Reference: https://ruby-doc.org/stdlib-2.5.1/libdoc/securerandom/rdoc/Random/Formatter.html

app/models/url_click.rb
class UrlClick < ApplicationRecord
    belongs_to :url
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  # Eg: http://localhost:3000/reports/api_all_urls
  # Eg: http://localhost:3000/reports/api_index

  # Get the required data when user visits the /reports page
  def index
    # Get all the UrlClicks along with their associated Urls for the detailed table
    @clicks = UrlClick.includes(:url).order(clicked_at: :desc)

    # Group the UrlClicks by the short_url and calculate total clicks for the summary table
    @shorten_urls = Url.joins(:url_clicks)
    .select("urls.*, COUNT(url_clicks.id) as total_clicks")
    .group("urls.id")
    .order("urls.id ASC")
  end

  def api_index
    @clicks = UrlClick.includes(:url).order(clicked_at: :desc)
    render json: @clicks.map { |click|
      {
        id: click.id,
        url_id: click.url_id,
        short_url: click.url.short_url,
        city: click.city,
        region: click.region,
        country: click.country,
        clicked_at: click.clicked_at,
        ip_address: click.ip_address
      }
    }
  end

  def api_all_urls
    @urls = Url.order(:id)

    render json: @urls.map { |url|
      {
        id: url.id,
        target_url: url.target_url,
        short_url: url.short_url,
        created_at: url.created_at,
        clicks: url.clicks,
        title: url.title
      }
    }
  end
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  protect_from_forgery except: :create
  rescue_from ActionController::Redirecting::UnsafeRedirectError do
    redirect_to root_url, alert: "Redirect to an unsafe URL detected."
  end

  def new
    # Form Data: When a user submits a form, the form data is sent to the server as part of the request.

    ## Clear flash messages after user has successfully shortened a URL
    flash.clear
    if params[:id]
      @url = Url.find(params[:id])
      flash[:notice] = "✅ URL successfully shortened!"
    else
      @url = Url.new
    end
    # This line renders the new template located at app/views/url/new.html.erb.
    # This template will display the form for creating a new URL.
    render template: "url/new"
  end

  def create
    @url = Url.new(url_params)
    @url.title = fetch_title(@url.target_url)

    if @url.save
      Rails.logger.info("URL saved with ID: #{@url.id}")
      redirect_to new_url_path(id: @url.id), notice: "URL successfully created!"
    else
      Rails.logger.error("URL save failed: #{@url.errors.full_messages.join(", ")}")
      respond_to do |format|
        format.html { render "url/new", status: :unprocessable_entity }  # Re-render the form with error messages
        format.json { render json: { errors: @url.errors.full_messages }, status: :unprocessable_entity }
      end
    end
  end

  def show
    @url = Url.find(params[:id])
    render json: {
      id: @url.id,
      target_url: @url.target_url,
      short_url: @url.short_url,
      title: @url.title
    }
  end

  def redirect
    if params[:short_url] == "reports"
      @clicks = UrlClick.includes(:url).order(clicked_at: :desc)
      @urls = Url.order(:id)
      render "reports/index"
    else
      url = Url.find_by!(short_url: params[:short_url])

      # Increment the clicks counter
      url.increment!(:clicks)

      geolocation = fetch_geolocation(request.remote_ip)
      UrlClick.create!(
        url: url,
        city: geolocation[:city],
        region: geolocation[:region],
        country: geolocation[:country],
        clicked_at: Time.current,
        ip_address: request.remote_ip,
      )

      redirect_to url.target_url
    end
  end

  private

  def url_params
    params.require(:url).permit(:target_url)
  end

  # Why ipinfo? Free plan with highest quota for free tier.
  def fetch_geolocation(ip_address)
    response = HTTP.get("https://ipinfo.io/#{ip_address}/json?token=#{ENV['IPINFO_API_TOKEN']}")
    if response.status.success?
      location_data = JSON.parse(response.body.to_s)
      {
        city: location_data["city"],
        region: location_data["region"],
        country: location_data["country"]
      }
    else
      {
        city: "Unknown",
        region: "Unknown",
        country: "Unknown"
      }
    end
  rescue StandardError => e
    Rails.logger.error "Geolocation fetch failed: #{e.message}"
    { city: "Unknown", region: "Unknown", country: "Unknown" }
  end

  def fetch_title(url)
    response = HTTP.get(url)
    if response.status.success?
      match = response.body.to_s.match(/<title>(.*?)<\/title>/)
      match ? match[1] : nil
    else
      nil
    end
  rescue HTTP::Error
    nil
  end

  def shortened_url(short_url)
    "#{request.base_url}/#{short_url}"
  end
end


# show: Finds a URL by id and redirects to its target_url.
# redirect: Finds a URL by short_url and redirects to its target_url, or redirects to the root URL with an alert if not found.
# url_params: Defines strong parameters for URL creation and updates.
# fetch_geolocation: Fetches geolocation data for an IP address using the IP-API service.

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/url_helper.rb
module UrlHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Url Shortener" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <!-- Simple Navigation Bar -->
    <nav class="bg-gray-200 fixed w-full top-0 z-10">
      <div class="max-w-7xl mx-auto px-2 sm:px-6 lg:px-8">
        <div class="flex justify-between h-16">
         
          <div class="flex space-x-4">
            <%= link_to 'Home', root_path, class: "text-gray-700 hover:bg-gray-300 hover:text-black px-3 py-2 rounded-md text-xl font-bold" %>
            <%= link_to 'Reports', reports_path, class: "text-gray-700 hover:bg-gray-300 hover:text-black px-3 py-2 rounded-md text-xl font-bold" %>
          </div>
        </div>
      </div>
    </nav>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/reports/index.html.erb
<!-- Tabs for Summary and Detailed Clicks -->
<div class="mt-10 max-w-7xl mx-auto">
  <div x-data="{ activeTab: 'summary' }">
    <div class="space-x-4 mb-4">
      <button @click="activeTab = 'summary'" :class="{ 'bg-blue-500 text-white': activeTab === 'summary' }" class="px-4 py-2 border rounded text-gray-700 bg-gray-200 mx-auto">
        Total URL Clicks
      </button>
      <button @click="activeTab = 'detailed'" :class="{ 'bg-blue-500 text-white': activeTab === 'detailed' }" class="px-4 py-2 border rounded text-gray-700 bg-gray-200 mx-auto">
        User Click Log (Desc Order)
      </button>
    </div>

    <!-- Summary Click Counts Table -->
    <div x-show="activeTab === 'summary'" class="overflow-hidden transition-all duration-300">
      <table id="shorten_urls" class="min-w-full bg-white border-collapse border border-gray-200">
        <thead>
          <tr>
            <th class="py-2 px-4 border-b border-gray-200 bg-gray-100 text-center text-sm uppercase font-bold text-gray-600">Index</th>
            <th class="py-2 px-4 border-b border-gray-200 bg-gray-100 text-center text-sm uppercase font-bold text-gray-600">Short URL</th>
            <th class="py-2 px-4 border-b border-gray-200 bg-gray-100 text-center text-sm uppercase font-bold text-gray-600">Original URL</th>
            <th class="py-2 px-4 border-b border-gray-200 bg-gray-100 text-center text-sm uppercase font-bold text-gray-600">Title Tag</th>
            <th class="py-2 px-4 border-b border-gray-200 bg-gray-100 text-center text-sm uppercase font-bold text-gray-600">Total Clicks</th>
          </tr>
        </thead>
        <tbody>
          <% if @urls.present? %>
            <% @urls.each_with_index do |url, index| %>
              <tr class="border-t border-gray-200">
                <td class="py-2 px-4 text-center"><%= index + 1 %></td>
                <td class="py-2 px-4 text-center">
                  <div class="truncate max-w-xs overflow-hidden whitespace-nowrap"><%= link_to url.short_url, shortened_url(url.short_url), class: "text-blue-500 underline" %></div>
                </td>
                <td class="py-2 px-4 text-center">
                  <div class="truncate max-w-xs overflow-hidden whitespace-nowrap"><%= link_to url.target_url, url.target_url, class: "text-blue-500 underline" %></div>
                </td>
                <td class="py-2 px-4 text-center"><%= url.title %></td>
                <td class="py-2 px-4 text-center"><%= url.clicks %></td>
              </tr>
            <% end %>
          <% else %>
            <tr>
              <td colspan="5" class="py-2 px-4 text-center text-gray-600">No summary records available.</td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <!-- Detailed Click Records Table -->
    <div x-show="activeTab === 'detailed'" class="overflow-hidden transition-all duration-300">
      <table id="clicks" class="min-w-full bg-white border-collapse border border-gray-200 mb-8">
        <thead>
          <tr>
            <th class="py-2 px-4 border-b border-gray-200 bg-gray-100 text-left text-sm uppercase font-bold text-gray-600">Index</th>
            <th class="py-2 px-4 border-b border-gray-200 bg-gray-100 text-left text-sm uppercase font-bold text-gray-600">Short URL</th>
            <th class="py-2 px-4 border-b border-gray-200 bg-gray-100 text-left text-sm uppercase font-bold text-gray-600">Original URL</th>
            <th class="py-2 px-4 border-b border-gray-200 bg-gray-100 text-left text-sm uppercase font-bold text-gray-600">City</th>
            <th class="py-2 px-4 border-b border-gray-200 bg-gray-100 text-left text-sm uppercase font-bold text-gray-600">Region</th>
            <th class="py-2 px-4 border-b border-gray-200 bg-gray-100 text-left text-sm uppercase font-bold text-gray-600">Country</th>
            <th class="py-2 px-4 border-b border-gray-200 bg-gray-100 text-left text-sm uppercase font-bold text-gray-600">Timestamp</th>
            <th class="py-2 px-4 border-b border-gray-200 bg-gray-100 text-left text-sm uppercase font-bold text-gray-600">IP Address</th>
          </tr>
        </thead>
        <tbody>
          <% if @clicks.present? %>
            <% @clicks.each_with_index do |click, index| %>
              <tr class="border-t border-gray-200">
                <td class="py-2 px-4 text-center"><%= index + 1 %></td>
                <td class="py-2 px-4 text-center">
                  <div class="truncate max-w-xs overflow-hidden whitespace-nowrap"><%= link_to click.url.short_url, shortened_url(click.url.short_url), class: "text-blue-500 underline" %></div>
                </td>
                <td class="py-2 px-4 text-center">
                  <div class="truncate max-w-xs overflow-hidden whitespace-nowrap"><%= link_to click.url.target_url, click.url.target_url, class: "text-blue-500 underline" %></div>
                </td>
                <td class="py-2 px-4 text-center"><%= click.city %></td>
                <td class="py-2 px-4 text-center"><%= click.region %></td>
                <td class="py-2 px-4 text-center"><%= click.country %></td>
                <td class="py-2 px-4 text-center"><%= click.clicked_at.strftime("%Y-%m-%d %H:%M:%S") %></td>
                <td class="py-2 px-4 text-center"><%= click.ip_address %></td>
              </tr>
            <% end %>
          <% else %>
            <tr>
              <td colspan="8" class="py-2 px-4 text-center text-gray-600">No click records available.</td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<!-- Add this script at the end of the page or in a separate JS file -->

<!-- Why alpine? - Lightweight, easy to implement, simple -->
<script src="https://cdn.jsdelivr.net/npm/alpinejs@2.8.2" defer></script>

app/views/url/create.html.erb
<h1>Url#create</h1>
<p>Find me in app/views/url/create.html.erb</p>

app/views/url/new.html.erb
<div class="flex flex-row items-start justify-center bg-gray-100 min-h-screen p-8">
  <!-- Left Side: URL Shortener Form -->
  <div class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4 w-full max-w-md mr-8" style="padding: 25px;">
    <h1 class="text-2xl font-bold mb-4">URL Shortener</h1>
    <!-- Flash Messages -->
    <% if flash[:notice] %>
      <div class="alert alert-success bg-green-500 text-white py-2 px-4 rounded mb-4">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-danger bg-red-500 text-white py-2 px-4 rounded mb-4">
        <%= flash[:alert] %>
      </div>
    <% end %>

    <!-- remote: true = async submit, no reload -->
    <%= form_with model: @url, url: urls_path, remote: true, id: "url-form" do |form| %>
      <% if @url.persisted? %>
        <!-- Display the shortened URL and other details after submission -->
        <div class="mb-4 text-left">
          <p class="text-gray-700">Original URL: <span class="font-semibold"><%= @url.target_url %></span></p>
          <p class="text-gray-700">Shortened URL: <span class="font-semibold"><%= link_to shortened_url(@url.short_url), shortened_url(@url.short_url), class: "text-blue-500 underline" %></span></p>
          <p class="text-gray-700">Title: <span class="font-semibold"><%= @url.title %></span></p>
        </div>
        <div class="flex space-x-4 mb-4">
          <button id="copy-button" type="button" class="bg-blue-500 text-white py-2 px-4 rounded w-full hover:bg-blue-700 cursor-pointer" onclick="copyToClipboard('<%= shortened_url(@url.short_url) %>')">Copy Shortened URL</button>
          <%= link_to 'Shorten Another URL', new_url_path, class: "bg-green-500 text-white py-2 px-4 rounded w-full hover:bg-green-700 cursor-pointer" %>
        </div>
      <% else %>
        <!-- Display the form if the URL is not yet shortened -->
        <div class="mb-4">
          <%= form.label :target_url, "Shorten a long URL", class: "block text-gray-700 text-sm font-bold mb-2" %>
          <%= form.text_field :target_url, placeholder: "Enter long link here", required: true, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
        </div>
        <div>
         <%= button_tag type: 'submit', class: "bg-blue-500 text-white py-2 px-4 rounded w-full hover:bg-blue-700 cursor-pointer" do %>
            Shorten URL
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>

  <!-- Right Side: Text Information -->
  <div class="text-left w-1/3" style="padding: 20px;">
    <h2 class="text-3xl font-bold text-gray-900 mb-4">URL Shortener</h2>
    <p class="text-gray-700 mb-4">
      Enter the long URL you want to shorten in the box on the left. Once shortened, you can copy the short URL and you will be able to track the number of clicks on the shortened URL.
    </p>
    <p class="text-gray-700 mb-4">Visit the <%= link_to 'Reports', reports_path, class: "text-blue-500 underline" %> to view analytics and statistics about your shortened URLs.</p>
  </div>
</div>

<!-- Add this script at the end of the page or in a separate JS file -->
<script src="https://cdn.jsdelivr.net/npm/alpinejs@2.8.2" defer></script>

<script>
  function copyToClipboard(text) {
    navigator.clipboard.writeText(text).then(function() {
      console.log("Text copied to clipboard: ", text); // Debugging log
      indicateCopySuccess();
    }, function(err) {
      console.error('Could not copy text: ', err);
    });
  }

  function indicateCopySuccess() {
    const copyButton = document.getElementById('copy-button');
    const originalText = copyButton.textContent;
    copyButton.textContent = 'Copied!';
    setTimeout(() => {
      copyButton.textContent = originalText;
    }, 2000); // Revert back after 2 seconds
  }
</script>

app/views/url/show.html.erb
<h1>Shortened URL</h1>
<p>Original URL: <%= @url.target_url %></p>
<p>Short URL: <%= url_for(@url) %></p>